# Site settings
title: The Stack
email: online@media.ucla.edu
description: > # this means to ignore newlines until next key
  The Stack is Daily Bruin’s data journalism and newsroom tech blog. We investigate
  public data, experiment with technology and apply quantitative insights to
  real life.
meta_description: > # shortened description for meta description tag
  Daily Bruin’s data journalism and newsroom tech blog. We investigate public
  data, experiment with technology and apply quantitative insights to real life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stack.dailybruin.com" # the base hostname & protocol for your site
image_url: /img/posts # corresponds to directory for post images (cf. https://github.com/opattison/jekyll-figure-image-tag#why-yaml-is-useful-for-storing-images)
twitter_username: _thestack
github_username:  dailybruin

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
      displayed: Yes

# Outputting
permalink: pretty # don't have `.html` on the end of permalinks
timezone: America/Los_Angeles
paginate: 12 # items per page
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

# plugins
gems: [jekyll-paginate]
